apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-weekmodel-vs
spec:
  hosts:
  - "weekmodel.hcl.softwarization.net"
  gateways:
  - istio-istio-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        port:
          number: 5000
        host: weekmodel.micro-system.svc.cluster.local

        